branches:
  only: master

cache:
  directories:
    - "node_modules"

language: node_js

node_js:
  - 6
  - 8

os: linux

env:
  - TARGET_REACT_VERSION=15
  - TARGET_REACT_VERSION=16

after_install:
  - npm uninstall react react-dom
  - npm install react@$(echo $TARGET_REACT_VERSION)
  - npm install react-dom@$(echo $TARGET_REACT_VERSION)

script:
  - npm test -- --coverage
  - npm run build
  - npm run size
  - codecov
